App\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
  properties:
    email:
      - Email: ~
      - NotBlank: ~
    password:
      - NotBlank: ~
      - Length:
          min: 8
          minMessage: 'Password should be at least {{ limit }} characters'
